# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Simon Hellmayr
tagline:             Things and Stuff
url:                 http://shellmayr.github.io
paginate:            1
baseurl:             ""
pages_list:
  About: '/about'
  Archive: '/archive'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Simon Hellmayr
  url:               https://twitter.com/shellmayr
  email:             simon.hellmayr@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/shellmayr/shellmayr.github.io
